# Generated by Django 3.0.8 on 2020-08-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(to='home.category'),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.ManyToManyField(to='home.location'),
        ),
    ]
